apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-basic-1776057056626
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/test-image:github-747c8385538e77904c2740046e92946e00630603
          name: container-image
